### ISSUE TITLE
Poor reconstruction for unseen samples

### ISSUE THREAD

**Issue by umang13** [AyanKumarBhunia/Self-Supervised-Learning-for-Sketch#4]
Hi, 
I am training the model to generate trajectories from handwritten text images. When I train the model to generate trajectories for IAMOnline images, the reconstructed images are pretty good for the samples it has been trained on. However, on trying to generate images from trajectories predicted for unseen samples, the images are quite poor. Any reason for this and ideas on how to get better generalization for unseen samples? 

Thanks

**Comment by AyanKumarBhunia** [comment]
Here, the objective is not to get high quality photo-to-sketch conversion. For Photo to sketch conversion (on handwritten images), please use something like this: https://github.com/AyanKumarBhunia/semisupervised-FGSBIR/blob/main/Photo_to_Sketch_2D_Attention/model.py#L40

or -- https://github.com/AyanKumarBhunia/sketch-transformerMMD
